[tool.ruff]
src = ["src", "test"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101",
    "ANN102",
    "ANN201",
    "ANN401",
    "COM",
    "D100",     # ignore missing module docstring
    "D104",     # ignore docstring in `__init__.py` function
    "D105",     
    "D107",
    "D203",
    "D213",
    "EM101",
    "EM103",
    "FA100",
    "FBT001",
    "FBT002",
    "ISC",
    "PLR0913",
    "PTH103",
    "PTH110",
    "PTH118",
    "PTH123",
    "PTH109",
    "SIM108",
    "S101",
    "TCH",
    "TRY003",
    "UP030",
    "UP032",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$" # Allow unused variables when underscore-prefixed.

[tool.ruff.format]
quote-style = "double"              # Like Black, use double quotes for strings.
indent-style = "space"              # Like Black, indent with spaces, rather than tabs.
skip-magic-trailing-comma = false   # Like Black, respect magic trailing commas.
line-ending = "auto"                # Like Black, automatically detect the appropriate line ending.

[tool.ruff.lint.pydocstyle]
convention = "google"